name: 🐛 Bug Report
description: Report a bug or unexpected behavior in LEANN
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        When I try to build an index with..., I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install LEANN with '...'
        2. Run command '...'
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The index should build successfully...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The process crashed with error...
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages or stack traces
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "...", line X, in <module>
            ...

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which backend are you using?
      options:
        - leann-backend-diskann
        - leann-backend-hnsw
        - Both
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: LEANN Version
      description: What version of LEANN are you using? (run `pip show leann`)
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu/Debian
        - Other Linux
        - Windows
        - Docker
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Please specify your OS version
      placeholder: "macOS 14.0, Ubuntu 22.04, etc."

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install LEANN?
      options:
        - pip install from PyPI
        - Built from source with uv
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Reproducible Example
      description: If possible, provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        from leann import LeannBuilder

        # Your code here

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., dataset size, memory constraints, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and followed the setup instructions
          required: true
        - label: I am using the latest version of LEANN (or have tested with it)
          required: false
