name: ✨ Feature Request
description: Suggest a new feature or enhancement for LEANN
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We're always looking for ways to improve LEANN.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm always frustrated when...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like LEANN to...
        The feature should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've tried using...
        Another approach could be...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of LEANN does this feature relate to?
      options:
        - Core API
        - DiskANN Backend
        - HNSW Backend
        - CLI Tools
        - Documentation
        - Performance
        - Testing
        - Build/Installation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Significantly improves workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would benefit you or others
      placeholder: |
        In my project, I need to...
        This would help when...
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: If applicable, show how you envision using this feature
      render: python
      placeholder: |
        from leann import LeannBuilder

        # How the API might look
        builder = LeannBuilder()
        builder.new_feature(...)

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: |
        This could be implemented by...
        We might need to modify...

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing APIs?
      options:
        - "No - Fully backward compatible"
        - "Yes - Would require API changes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false
        - label: I have searched existing issues and this is not a duplicate
          required: true
